/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.Controller;
import domain.Korisnik;
import domain.Nalog;
import domain.Objekat;
import domain.Vozac;
import domain.Vozilo;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FrmDodajNalog extends javax.swing.JDialog {

    /**
     * Creates new form FrmDodajNalog
     */
    public FrmDodajNalog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            prepareView();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom pripreme forme!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProduct1 = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        brnaloga = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtnapomena = new javax.swing.JTextField();
        lblPrice1 = new javax.swing.JLabel();
        cmbMagacin = new javax.swing.JComboBox();
        lblName3 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblPrice2 = new javax.swing.JLabel();
        cmbMaloprodaja = new javax.swing.JComboBox();
        lblPrice3 = new javax.swing.JLabel();
        cmbKorisnik = new javax.swing.JComboBox();
        lblPrice4 = new javax.swing.JLabel();
        lblPrice5 = new javax.swing.JLabel();
        lblPrice6 = new javax.swing.JLabel();
        txtnapomena1 = new javax.swing.JTextField();
        cmbVozac = new javax.swing.JComboBox();
        cmbVozilo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelProduct1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nalog"));

        lblID1.setText("broj naloga:");

        lblName2.setText("napomena");

        lblPrice1.setText("magacin");

        cmbMagacin.setEditable(true);
        cmbMagacin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMagacinActionPerformed(evt);
            }
        });

        lblName3.setText("datum(YYYY-MM-DD)");

        btnIzmeni.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnIzmeni.setText("Dodaj");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        lblPrice2.setText("maloprodaja:");

        cmbMaloprodaja.setEditable(true);
        cmbMaloprodaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMaloprodajaActionPerformed(evt);
            }
        });

        lblPrice3.setText("Korisnik");

        cmbKorisnik.setEditable(true);
        cmbKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKorisnikActionPerformed(evt);
            }
        });

        lblPrice4.setText("Vozac");

        lblPrice5.setText("Vozilo");

        lblPrice6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPrice6.setText("Ukupna Vrednost:");

        txtnapomena1.setEditable(false);

        cmbVozac.setEditable(true);
        cmbVozac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVozacActionPerformed(evt);
            }
        });

        cmbVozilo.setEditable(true);
        cmbVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVoziloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProduct1Layout = new javax.swing.GroupLayout(panelProduct1);
        panelProduct1.setLayout(panelProduct1Layout);
        panelProduct1Layout.setHorizontalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblID1)
                            .addComponent(lblName2))
                        .addGap(54, 54, 54)
                        .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brnaloga)
                            .addComponent(txtnapomena)))
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOtkazi)
                .addGap(42, 42, 42))
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrice1)
                .addGap(82, 82, 82)
                .addComponent(cmbMagacin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrice2)
                .addGap(46, 46, 46)
                .addComponent(cmbMaloprodaja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrice3)
                .addGap(85, 85, 85)
                .addComponent(cmbKorisnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addComponent(lblPrice6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnapomena1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440))
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addComponent(lblPrice4)
                        .addGap(100, 100, 100)
                        .addComponent(cmbVozac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addComponent(lblPrice5)
                        .addGap(98, 98, 98)
                        .addComponent(cmbVozilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelProduct1Layout.setVerticalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(brnaloga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName3)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txtnapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice1)
                    .addComponent(cmbMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice2)
                    .addComponent(cmbMaloprodaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice3)
                    .addComponent(cmbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice4)
                    .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice5)
                    .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice6)
                    .addComponent(txtnapomena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOtkazi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMagacinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMagacinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMagacinActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            Nalog nalog=new Nalog();
            nalog.setBrojNaloga(brnaloga.getText().trim());
            jDateChooser2.setDateFormatString("yyyy-MM-dd");
            java.util.Date jud=jDateChooser2.getDate();
            java.sql.Date jsd=new java.sql.Date(jud.getTime());
            
            nalog.setDatum(jsd);
            nalog.setKorisnik((Korisnik) cmbKorisnik.getSelectedItem());
            nalog.setMagacin((Objekat) cmbMagacin.getSelectedItem());
            nalog.setMaloprodaja((Objekat) cmbMaloprodaja.getSelectedItem());
            nalog.setNapomena(txtnapomena.getText().trim());
            nalog.setVozac((Vozac) cmbVozac.getSelectedItem());
            nalog.setVozilo((Vozilo) cmbVozilo.getSelectedItem());
            
            
       
             Controller.getInstance().addNalog(nalog);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio nalog.", "Uspešno čuvanje nalog", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Sistem ne može da zapamti nalog", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void cmbMaloprodajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMaloprodajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaloprodajaActionPerformed

    private void cmbKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKorisnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKorisnikActionPerformed

    private void cmbVozacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVozacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVozacActionPerformed

    private void cmbVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVoziloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVoziloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDodajNalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDodajNalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDodajNalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDodajNalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDodajNalog dialog = new FrmDodajNalog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brnaloga;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbKorisnik;
    private javax.swing.JComboBox cmbMagacin;
    private javax.swing.JComboBox cmbMaloprodaja;
    private javax.swing.JComboBox cmbVozac;
    private javax.swing.JComboBox cmbVozilo;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    private javax.swing.JLabel lblPrice4;
    private javax.swing.JLabel lblPrice5;
    private javax.swing.JLabel lblPrice6;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JTextField txtnapomena;
    private javax.swing.JTextField txtnapomena1;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
       pripremiComboMagacin();
       pripremiComboMaloprodaja();
       pripremiComboVozac();
       pripremiComboVozilo();
      
       pripremiComboKorisnik();
    }

    private void pripremiComboMagacin() throws Exception {
        List<Objekat> lista = Controller.getInstance().getAllObjekti();
        cmbMagacin.removeAllItems();
        for (Objekat jm : lista) {
            cmbMagacin.addItem(jm);
    }
    
    }

    private void pripremiComboMaloprodaja() throws Exception {
       List<Objekat> lista = Controller.getInstance().getAllObjekti();
        cmbMaloprodaja.removeAllItems();
        for (Objekat jm : lista) {
            cmbMaloprodaja.addItem(jm);
    }
    }

    private void pripremiComboVozac() throws Exception {
        List<Vozac> lista = Controller.getInstance().getAllVozac();
        cmbVozac.removeAllItems();
        for (Vozac jm : lista) {
            cmbVozac.addItem(jm);
    }
    }

    private void pripremiComboVozilo() throws Exception {
       List<Vozilo> lista = Controller.getInstance().getAllVozilo();
        cmbVozilo.removeAllItems();
        for (Vozilo jm : lista) {
            cmbVozilo.addItem(jm);
    }
    }
     

    private void pripremiComboKorisnik() throws Exception {
       List<Korisnik> lista = Controller.getInstance().getAllKorisnik();
        cmbKorisnik.removeAllItems();
        for (Korisnik jm : lista) {
            cmbKorisnik.addItem(jm);
    }
    }
}
