/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Adresa;
import domain.JedinicaMere;
import domain.Mesto;
import domain.Roba;
import java.util.List;
import javax.swing.JOptionPane;
import validation.Validator;

/**
 *
 * @author Korisnik
 */
public class FrmDodajAdresu extends javax.swing.JDialog {

    /**
     * Creates new form FrmDodajAdresu
     */
    public FrmDodajAdresu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         try {
            prepareView();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom pripreme forme!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProduct1 = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        txtbruliceprim = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        cmbJM1mes = new javax.swing.JComboBox();
        lblManufacturer1 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        txtnazivUlice = new javax.swing.JTextField();
        txtnazivmesta = new javax.swing.JTextField();
        txtbroj = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelProduct1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresa"));

        lblID1.setText("broj ulice:");

        lblName2.setText("postanski broj:");

        lblPrice1.setText("broj:");

        cmbJM1mes.setEditable(true);
        cmbJM1mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJM1mesActionPerformed(evt);
            }
        });

        lblManufacturer1.setText("Naziv mesta:");

        lblName3.setText("naziv ulice");

        txtnazivmesta.setEditable(false);
        txtnazivmesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnazivmestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProduct1Layout = new javax.swing.GroupLayout(panelProduct1);
        panelProduct1.setLayout(panelProduct1Layout);
        panelProduct1Layout.setHorizontalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice1)
                    .addComponent(lblManufacturer1)
                    .addComponent(lblName2)
                    .addComponent(lblID1)
                    .addComponent(lblName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnazivUlice)
                            .addComponent(txtbruliceprim)
                            .addComponent(cmbJM1mes, 0, 475, Short.MAX_VALUE)
                            .addComponent(txtnazivmesta))
                        .addContainerGap())
                    .addComponent(txtbroj, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        panelProduct1Layout.setVerticalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(txtbruliceprim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName2)
                    .addComponent(cmbJM1mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(txtnazivUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice1)
                    .addComponent(txtbroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer1)
                    .addComponent(txtnazivmesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        btnIzmeni.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnIzmeni.setText("Dodaj");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(btnOtkazi)
                .addGap(114, 114, 114))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(panelProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(panelProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbJM1mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJM1mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJM1mesActionPerformed

    private void txtnazivmestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnazivmestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnazivmestaActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
try {
            Validator.startValidation()
            .validateNotNullOrEmpty(txtbruliceprim.getText(), "broj ulice je obavezno polje")
            .validateNotNullOrEmpty(txtnazivUlice.getText(), "naziv uluce je obavezno polje")
            .throwIfInvalide();
            
           Adresa a= new Adresa();
            a.setBroj(Integer.parseInt(txtbroj.getText().trim()));
            a.setBrojUlice(Integer.parseInt(txtbruliceprim.getText().trim()));
            a.setNazivMesta(txtnazivmesta.getText().trim());
            a.setUlica(txtnazivUlice.getText().trim());
            a.setPostanskiBroj((Mesto) cmbJM1mes.getSelectedItem());
            Controller.getInstance().addAdresa(a);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio adresu.", "Uspešno čuvanje adresu", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Sistem ne može da zapamti adresu", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDodajAdresu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDodajAdresu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDodajAdresu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDodajAdresu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDodajAdresu dialog = new FrmDodajAdresu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbJM1mes;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblManufacturer1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JTextField txtbroj;
    private javax.swing.JTextField txtbruliceprim;
    private javax.swing.JTextField txtnazivUlice;
    private javax.swing.JTextField txtnazivmesta;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
       pripremiCombo();
    }

    private void pripremiCombo() throws Exception {
        List<Mesto> listame = Controller.getInstance().getAllMesta();
        cmbJM1mes.removeAllItems();
        for (Mesto jm : listame) {
            cmbJM1mes.addItem(jm);
    }
    
}}
