/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.JedinicaMere;
import domain.Roba;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FrmIzmeniRobu extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmeniRobu
     */
    public FrmIzmeniRobu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            prepareView();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom pripreme forme!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProduct = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtsifrarobe = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtnazivRobe = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        cmbJM = new javax.swing.JComboBox();
        lblManufacturer = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        txtbarkod = new javax.swing.JTextField();
        txtnazivJM = new javax.swing.JTextField();
        panelProduct1 = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        txtsifrarobe1 = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtnazivRobe1 = new javax.swing.JTextField();
        lblPrice1 = new javax.swing.JLabel();
        cmbJM1 = new javax.swing.JComboBox();
        lblManufacturer1 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        txtbarkod1 = new javax.swing.JTextField();
        txtnazivJM1 = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        panelProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Roba"));

        lblID.setText("sifra robe:");

        lblName.setText("naziv robe:");

        lblPrice.setText("Jedinica mere(SIfra): ");

        lblManufacturer.setText("Naziv jedinice mere:");

        lblName1.setText("barkod:");

        txtnazivJM.setEditable(false);
        txtnazivJM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnazivJMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductLayout = new javax.swing.GroupLayout(panelProduct);
        panelProduct.setLayout(panelProductLayout);
        panelProductLayout.setHorizontalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(lblManufacturer)
                            .addComponent(lblName)
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsifrarobe)
                            .addComponent(txtnazivRobe)
                            .addComponent(cmbJM, 0, 531, Short.MAX_VALUE)
                            .addComponent(txtnazivJM)))
                    .addGroup(panelProductLayout.createSequentialGroup()
                        .addComponent(lblName1)
                        .addGap(105, 105, 105)
                        .addComponent(txtbarkod)))
                .addContainerGap())
        );
        panelProductLayout.setVerticalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtsifrarobe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtnazivRobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtbarkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(cmbJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtnazivJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelProduct1.setBorder(javax.swing.BorderFactory.createTitledBorder("Roba"));

        lblID1.setText("sifra robe:");

        txtsifrarobe1.setEditable(false);

        lblName2.setText("naziv robe:");

        lblPrice1.setText("Jedinica mere(SIfra): ");

        cmbJM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJM1ActionPerformed(evt);
            }
        });

        lblManufacturer1.setText("Naziv jedinice mere:");

        lblName3.setText("barkod:");

        txtnazivJM1.setEditable(false);
        txtnazivJM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnazivJM1ActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProduct1Layout = new javax.swing.GroupLayout(panelProduct1);
        panelProduct1.setLayout(panelProduct1Layout);
        panelProduct1Layout.setHorizontalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice1)
                            .addComponent(lblManufacturer1)
                            .addComponent(lblName2)
                            .addComponent(lblID1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsifrarobe1)
                            .addComponent(txtnazivRobe1)
                            .addComponent(cmbJM1, 0, 531, Short.MAX_VALUE)
                            .addComponent(txtnazivJM1)))
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addComponent(lblName3)
                        .addGap(105, 105, 105)
                        .addComponent(txtbarkod1)))
                .addContainerGap())
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOtkazi)
                .addGap(42, 42, 42))
        );
        panelProduct1Layout.setVerticalGroup(
            panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(txtsifrarobe1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txtnazivRobe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(txtbarkod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice1)
                    .addComponent(cmbJM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnazivJM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManufacturer1))
                .addGroup(panelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelProduct1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnazivJMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnazivJMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnazivJMActionPerformed

    private void txtnazivJM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnazivJM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnazivJM1ActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
      
         try {
            Roba roba= new Roba();
            roba.setSifraRobe(Integer.parseInt(txtsifrarobe1.getText().trim()));
            roba.setNazivRobe(txtnazivRobe1.getText().trim());
            roba.setBarKod(Long.parseLong(txtbarkod1.getText().trim()));
            roba.setJedinicaMere((JedinicaMere) cmbJM1.getSelectedItem());
            Controller.getInstance().editRoba(roba);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio robu.", "Uspešno čuvanje robe", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
           
           JOptionPane.showMessageDialog(this,"Sistem ne može da zapamti robu","Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void cmbJM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJM1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRobu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRobu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRobu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRobu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmIzmeniRobu dialog = new FrmIzmeniRobu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     private void prepareView() throws Exception {
       pripremiComboRoba();
    }

    private void pripremiComboRoba() throws Exception {
        List<JedinicaMere> listaJm = Controller.getInstance().getAllJedinicaMere();
        cmbJM1.removeAllItems();
        for (JedinicaMere jm : listaJm) {
            cmbJM1.addItem(jm);
    }
    
     
    }

    void setRoba(Roba roba) {
       
        txtsifrarobe1.setText(String.valueOf(roba.getSifraRobe()));
        txtnazivRobe1.setText(roba.getNazivRobe());
        txtbarkod1.setText(String.valueOf(roba.getBarKod())); 
        cmbJM1.setSelectedItem(roba.getJedinicaMere());
    txtnazivJM1.setText(roba.getNazivJediniceMere());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbJM;
    private javax.swing.JComboBox cmbJM1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufacturer1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JPanel panelProduct;
    private javax.swing.JPanel panelProduct1;
    private javax.swing.JTextField txtbarkod;
    private javax.swing.JTextField txtbarkod1;
    private javax.swing.JTextField txtnazivJM;
    private javax.swing.JTextField txtnazivJM1;
    private javax.swing.JTextField txtnazivRobe;
    private javax.swing.JTextField txtnazivRobe1;
    private javax.swing.JTextField txtsifrarobe;
    private javax.swing.JTextField txtsifrarobe1;
    // End of variables declaration//GEN-END:variables
}
