/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Objekat;
import domain.Rashod;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FrmIzmeniRashod extends javax.swing.JDialog {

    /**
     * Creates new form FrmIzmeniRashod
     */
    public FrmIzmeniRashod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            prepareView();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška prilikom pripreme forme!", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        panelProduct7 = new javax.swing.JPanel();
        lblID6 = new javax.swing.JLabel();
        txtbrr = new javax.swing.JTextField();
        lblName12 = new javax.swing.JLabel();
        txtnap = new javax.swing.JTextField();
        lblPrice6 = new javax.swing.JLabel();
        cmbso = new javax.swing.JComboBox();
        lblName13 = new javax.swing.JLabel();
        btnIzmeni5 = new javax.swing.JButton();
        btnOtkazi5 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelProduct7.setBorder(javax.swing.BorderFactory.createTitledBorder("Rashod"));

        lblID6.setText("broj rashoda:");

        txtbrr.setEditable(false);

        lblName12.setText("napomena");

        lblPrice6.setText("sifra Objekta");

        cmbso.setEditable(true);
        cmbso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsoActionPerformed(evt);
            }
        });

        lblName13.setText("datum");

        btnIzmeni5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnIzmeni5.setText("Izmeni");
        btnIzmeni5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeni5ActionPerformed(evt);
            }
        });

        btnOtkazi5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOtkazi5.setText("Otkazi");
        btnOtkazi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkazi5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProduct7Layout = new javax.swing.GroupLayout(panelProduct7);
        panelProduct7.setLayout(panelProduct7Layout);
        panelProduct7Layout.setHorizontalGroup(
            panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice6)
                    .addComponent(lblName12)
                    .addComponent(lblID6)
                    .addComponent(lblName13))
                .addGap(54, 54, 54)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbrr)
                    .addComponent(txtnap)
                    .addComponent(cmbso, 0, 874, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelProduct7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnIzmeni5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOtkazi5)
                .addGap(42, 42, 42))
        );
        panelProduct7Layout.setVerticalGroup(
            panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduct7Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID6)
                    .addComponent(txtbrr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName12)
                    .addComponent(txtnap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice6)
                    .addComponent(cmbso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName13)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(panelProduct7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOtkazi5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnIzmeni5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelProduct7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsoActionPerformed

    private void btnIzmeni5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeni5ActionPerformed

        try {
            Rashod r= new Rashod();
            r.setBrojRashoda(txtbrr.getText().trim());
            r.setNapomena(txtnap.getText().trim());
            //r.setDa
            jDateChooser2.setDateFormatString("yyyy-MM-dd");
           java.util.Date jud=jDateChooser2.getDate();
           java.sql.Date jsd=new java.sql.Date(jud.getTime());
           r.setDatum(jsd);
            //r.setDatum();
           r.setSifraObjekta((Objekat) cmbso.getSelectedItem());
           Controller.getInstance().editRashod(r);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio rashod.", "Uspešno čuvanje rasho", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,"Sistem ne može da zapamti rashod","Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeni5ActionPerformed

    private void btnOtkazi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkazi5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkazi5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRashod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRashod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRashod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIzmeniRashod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmIzmeniRashod dialog = new FrmIzmeniRashod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    void setRashod(Rashod r) {
        txtbrr.setText(r.getBrojRashoda());
        txtnap.setText(r.getNapomena());
        cmbso.setSelectedItem(r.getSifraObjekta());
        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setDate(r.getDatum());
         //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
         //java.sql.Date sqlDate = new java.sql.Date (r.getDatum().getTime());
        //txtdat.setText(sdf.format(sqlDate));
         
  
            
       
        ;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni5;
    private javax.swing.JButton btnOtkazi5;
    private javax.swing.JComboBox cmbso;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel lblID6;
    private javax.swing.JLabel lblName12;
    private javax.swing.JLabel lblName13;
    private javax.swing.JLabel lblPrice6;
    private javax.swing.JPanel panelProduct7;
    private javax.swing.JTextField txtbrr;
    private javax.swing.JTextField txtnap;
    // End of variables declaration//GEN-END:variables

   private void prepareView() throws Exception {
       pripremiComboR();
    }

    private void pripremiComboR() throws Exception {
        List<Objekat> lista = Controller.getInstance().getAllObjekti();
        cmbso.removeAllItems();
        for (Objekat jm : lista) {
            cmbso.addItem(jm);
    }
    
     
    }
}
