/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import thread.SatNit;

/**
 *
 * @author Korisnik
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
         prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLablevreme = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLablevremeglavna = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRoba = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmenuJM = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Adresa = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVozilo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuVOZAC = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuRashod = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Pregled = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jLablevreme.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLablevreme.setText("Trenutno vreme: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 2, 100)); // NOI18N
        jLabel1.setText("Dobrodošli! ");

        jLablevremeglavna.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLablevremeglavna.setText("Trenutno vreme: ");

        jMenuRoba.setText("Roba");

        jMenuItem1.setText("Pregled");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRoba.add(jMenuItem1);

        jMenuBar1.add(jMenuRoba);

        jmenuJM.setText("JedinicaMere");
        jmenuJM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuJMActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Pregled");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmenuJM.add(jMenuItem2);

        jMenuBar1.add(jmenuJM);

        jMenu1.setText("Mesto");

        jMenuItem3.setText("Pregled");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        Adresa.setText("Adresa");

        jMenuItem4.setText("Pregled");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Adresa.add(jMenuItem4);

        jMenuBar1.add(Adresa);

        jMenu2.setText("Vozilo");

        jMenuItemVozilo.setText("Pregled");
        jMenuItemVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVoziloActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVozilo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vozac");

        jMenuVOZAC.setText("Pregled");
        jMenuVOZAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVOZACActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuVOZAC);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Rashod");

        jMenuRashod.setText("Pregled");
        jMenuRashod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRashodActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuRashod);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Kupac");

        Pregled.setText("Pregled");
        Pregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledActionPerformed(evt);
            }
        });
        jMenu5.add(Pregled);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Nalog");

        jMenuItem6.setText("Pregled");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Stavka naloga");

        jMenuItem5.setText("Pregled");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Prenosnica");

        jMenuItem7.setText("Pregled");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablevremeglavna))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLablevremeglavna, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FrmPrikaziSvuRobu fpr = new FrmPrikaziSvuRobu(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmenuJMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuJMActionPerformed
      
    }//GEN-LAST:event_jmenuJMActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FRMPrikaziMere fpr = new FRMPrikaziMere(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);  
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmPrikaziMesta fpr = new FrmPrikaziMesta(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmPrikaziAdrese fpr = new FrmPrikaziAdrese(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoziloActionPerformed
       FrmPrikaziVozila fpr = new FrmPrikaziVozila(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItemVoziloActionPerformed

    private void jMenuVOZACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVOZACActionPerformed
         FrmPrikaziVozace fpr = new FrmPrikaziVozace(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuVOZACActionPerformed

    private void jMenuRashodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRashodActionPerformed
         FrmPrikaziRashod fpr = new FrmPrikaziRashod(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuRashodActionPerformed

    private void PregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledActionPerformed
         FrmPrikaziKupce fpr = new FrmPrikaziKupce(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_PregledActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmPrikaziStavkeNaloga fpr = new FrmPrikaziStavkeNaloga(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmPrikaziNalog fpr = new FrmPrikaziNalog(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmPrikaziPrenosnica fpr = new FrmPrikaziPrenosnica(this, true);
        fpr.setLocationRelativeTo(null);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Adresa;
    private javax.swing.JMenuItem Pregled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLablevreme;
    private javax.swing.JLabel jLablevremeglavna;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemVozilo;
    private javax.swing.JMenuItem jMenuRashod;
    private javax.swing.JMenu jMenuRoba;
    private javax.swing.JMenuItem jMenuVOZAC;
    private javax.swing.JMenu jmenuJM;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
         Thread vremeNit = new Thread(new SatNit(jLablevremeglavna));
        vremeNit.start();
    }
}
